
server:
  port: 8000
  servlet:
    context-path: /blog
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create # 서버 실행 시 테이블을 어떻게 할지 정하는 것 (create는 다시 만든다는 뜻)
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # Entity(테이블)을 만들 때 변수명을 그대로 테이블에 넣는다
      use-new-id-generator-mappings: false # JPA에 기본전략을 따라가지 않겠다(false)
    show-sql: true # 콘솔에 테이블 쿼리문을 보여줌(true)
    properties:
      hibernate.format_sql: true # 쿼리문을 한줄이 아니라 여러줄로 가독성 있게 표시됨(true)

  jackson:
    serialization:
      fail-on-empty-beans: false